# Configuración de la aplicación
spring.application.name=BackendForoUPC

# Conexión con PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/portal_turismo
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Directiva JPA para actualizar/generar tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Mostrar sentencias SQL formateadas en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar open-in-view warning
spring.jpa.open-in-view=false

# Configuración de JWT
jwt.secret=9a6747f3b64c61d4a607645061ce7212513a94f55393b2cef440355125a4e921
jwt.expiration=86400000

# Configuración de Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
